apiVersion: {{ ternary "storage.k8s.io/v1" "storage.k8s.io/v1beta1" (semverCompare ">=1.18.0-0" .Capabilities.KubeVersion.Version) }}
kind: CSIDriver
metadata:
  name: fsx.csi.aws.com
spec:
  attachRequired: {{ .Values.csidriver.attachRequired }}
  fsGroupPolicy: {{ .Values.csidriver.fsGroupPolicy }}
  podInfoOnMount: {{ .Values.csidriver.podInfoOnMount }}
  requiresRepublish: {{ .Values.csidriver.requiresRepublish }}
  storageCapacity: {{ .Values.csidriver.storageCapacity }}
  volumeLifecycleModes: 
  {{- range .Values.csidriver.volumeLifecycleModes }}
  - {{.}}
  {{- end }}
